export const CHANGE_PROFILE_DATA = 'profile/CHANGE_PROFILE_DATA' 

export const CHANGE_TABS_ACTIVEKEY = 'profile/CHANGE_TABS_ACTIVEKEY'
export const CHANGE_ATTEN_TABS_ACTIVEKEY = 'profile/CHANGE_ATTEN_TABS_ACTIVEKEY'

export const CHANGE_FOLLOW_FLAG = 'profile/CHANGE_FOLLOW_FLAG'
export const CHANGE_FOLLOWED_FLAG = 'profile/CHANGE_FOLLOWED_FLAG'

