export const TIGGER_LOGIN_OR_REGISTER = 'TIGGER_LOGIN_OR_REGISTER'
export const INPUT_CHANGE_ACTION = 'INPUT_CHANGE_ACTION'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'